
# This is the configuration used to check the rubocop source code.
# It was based in some configurations from: https://github.com/bbatsov/rubocop/tree/master/config

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
